### ISSUE TITLE
Research and Implement Router alternative

### ISSUE THREAD

**Issue by mxkay** [mxkay/forgotten-frontend#12]
React Router does not exist in React Native. We need to research the alternatives and set up App.js accordingly.

**Comment by Dychotomy** [comment]
After some research we are using react navigation as our solution for navigation. I some how broke Mohammad's code when we tried integrating it, not sure what was wrong. However there is a working version of the navigation under the nav-test branch. Several things of note. First don't merge it yet, the code needs to be cleaned up a bit. Second I changed Nav to Layout, it fits closer to the react architecture that was designed out.

**Comment by Dychotomy** [comment]
Made a pull request.
