### ISSUE TITLE
Create Post component

### ISSUE THREAD

**Issue by mxkay** [mxkay/forgotten-frontend#16]
This component will take a required prop of transactionData. This component will display the transactionData similarly to the wireframes below.

![post](https://user-images.githubusercontent.com/63630918/87968633-b8a1ce00-ca8e-11ea-9584-f9d63bc340ba.png)

BONUS: This component would ideally expand when selected to display additional information.

**Comment by Dychotomy** [comment]
We have a functional Post component. This should be revisited to be style so they can expand.
