### ISSUE TITLE
Create PostForm component

### ISSUE THREAD

**Issue by mxkay** [mxkay/forgotten-frontend#27]
This component should take an optional prop called postData, which is an object containing the keys listed below. If postData is given, use it to fill the form inputs on mount.

This component should contain a form with inputs to fill the following information

```
name, // of item
icon,
value,
transactionDate
returnDate,
description,
lenderID, // search for lender based on handle
lenderName, // used if lenderID is not available
borrowerID, // search for lender based on handle
borrowerName, // used if lenderID is not available
```
This component should take an handleSubmit prop. When calling handleSubmit, pass it all of the above data. This information will be used in the parent component to either create a new post or update a an existing post.

This component should also contain buttons for delete and cancel. Only display these buttons if passed handleDelete and handleCancel props, respectively.

**Comment by Dychotomy** [comment]
EditPost and PostForm were merged.
