### ISSUE TITLE
Create NewPost component

### ISSUE THREAD

**Issue by mxkay** [mxkay/forgotten-frontend#28]
This component should contain PostForm as a child. Pass PostForm the following props.
```
handleSubmit
handleCancel
```
The handleSubmit function should take an object as an argument containing the following keys.
```
name, // of item
icon,
value,
transactionDate
returnDate,
description,
lenderID, // search for lender based on handle
lenderName, // used if lenderID is not available
borrowerID, // search for lender based on handle
borrowerName, // used if lenderID is not available
```
Use this information to make an API call to create a new post in the database.

The handleCancel function should redirect back to Home.

**Comment by wt08** [comment]
newpost complete
