### ISSUE TITLE
Create the EditPost component

### ISSUE THREAD

**Issue by mxkay** [mxkay/forgotten-frontend#30]
The component should take a post _id as a prop. On mount, this component should make an API call to GET the post from the backend and store it to postData.

This component should contain PostForm as a child. Pass PostForm the following props.
```
postData
handleSubmit
handleDelete
handleCancel
```
The handleSubmit function should take an object as an argument containing the following keys.
```
name, // of item
icon,
value,
transactionDate
returnDate,
description,
lenderID, // search for lender based on handle
lenderName, // used if lenderID is not available
borrowerID, // search for lender based on handle
borrowerName, // used if lenderID is not available
```
Use this information to make an API call to create a new post in the database.

The handleCancel function should redirect back to Home.

**Comment by Dychotomy** [comment]
EditPost and PostForm were merged.
