### ISSUE TITLE
Create Login component

### ISSUE THREAD

**Issue by mxkay** [mxkay/forgotten-frontend#9]
The Login component should contain two forms: SignIn and CreateAccount.

SignIn should take a user's handle. On submit, it should make an API call to check whether a user exists with that handle. If that API call is successful, it should update the useContext variable (this is dependent on setting up useContext).

CreateAccount should take a name, handle, and email address. On submit, it should validate the inputs, and then make the same API call as above to check if the handle is taken.

If the handle is available, create a new user in the database; else display a message to the user to chose a different handle.

**Comment by wt08** [comment]
The Login component now has 2 forms.

The first form asks for a user's handle, and stores the back-end object associated with that user in a new variable.

The second form is for creating a new account. It asks for name, handle, and password. On submit, the inputs are used to create a new user on the backend.

The Login component is NOT READY to be merged to the main branch. It requires further discussion from the group first.

**Comment by wt08** [comment]
Login now fully functioning. Just need useContext for passing down variables and routes to link to other pages.
